CREATE TABLE IF NOT EXISTS rejected_payments (
    id INT AUTO_INCREMENT PRIMARY KEY,
    booking_id INT NOT NULL,
    customer_id INT NULL,
    name VARCHAR(150) NULL,
    email VARCHAR(190) NULL,
    phone VARCHAR(60) NULL,
    booking_date DATE NULL,
    booking_time_from VARCHAR(20) NULL,
    booking_time_until VARCHAR(20) NULL,
    visitors INT NULL,
    total DECIMAL(12,2) NULL,
    amount_to_pay DECIMAL(12,2) NULL,
    payment_status VARCHAR(40) NOT NULL DEFAULT 'pending_retry',
    payment_reason TEXT NULL,
    preference_id VARCHAR(120) NULL,
    payment_id VARCHAR(120) NULL,
    external_reference VARCHAR(120) NULL,
    retry_url TEXT NULL,
    notified_at DATETIME NULL,
    expires_at DATETIME NULL,
    closed_at DATETIME NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    KEY idx_rejected_payments_booking_id (booking_id),
    KEY idx_rejected_payments_status (payment_status),
    KEY idx_rejected_payments_expires_at (expires_at),
    KEY idx_rejected_payments_created_at (created_at),
    KEY idx_rejected_payments_preference_id (preference_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
